-- Generated by tools/ingest-commons-images.mjs. Do not hand-edit.
--
-- All photographs are freely licensed (CC BY / CC BY-SA) from Wikimedia
-- Commons. The licence requires attribution, which the credit column carries
-- and the UI renders. Images were resized and recompressed; that change is
-- disclosed on /licences.

delete from ganpati_images where url like '/mandals/%';

insert into ganpati_images (ganpati_id, url, alt, credit, width, height, sort_order, is_primary)
select g.id, v.url, v.alt, v.credit, v.width, v.height, v.sort_order, v.is_primary
from (values
  ('dagdusheth-halwai-ganpati', '/mandals/dagdusheth-halwai-ganpati/1.jpg', 'Shrimant Dagdusheth Halwai Ganpati, Pune', 'Universalashic / CC BY-SA 3.0 via Wikimedia Commons', 1200, 1600, 0, true),
  ('dagdusheth-halwai-ganpati', '/mandals/dagdusheth-halwai-ganpati/2.jpg', 'Shrimant Dagdusheth Halwai Ganpati, Pune', 'Universalashic / CC BY-SA 3.0 via Wikimedia Commons', 1200, 1600, 1, false),
  ('dagdusheth-halwai-ganpati', '/mandals/dagdusheth-halwai-ganpati/3.jpg', 'Shrimant Dagdusheth Halwai Ganpati, Pune', 'Ketaki Pole / CC BY-SA 3.0 via Wikimedia Commons', 1200, 1600, 2, false),
  ('kasba-ganpati', '/mandals/kasba-ganpati/1.jpg', 'Shri Kasba Ganpati, Pune', 'Universalashic / CC BY-SA 3.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('tambdi-jogeshwari', '/mandals/tambdi-jogeshwari/1.jpg', 'Tambdi Jogeshwari Ganpati, Pune', 'Pakshya / CC BY-SA 3.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('tambdi-jogeshwari', '/mandals/tambdi-jogeshwari/2.jpg', 'Tambdi Jogeshwari Ganpati, Pune', 'ANI(GM) / CC BY-SA 3.0 via Wikimedia Commons', 1200, 2137, 1, false),
  ('tambdi-jogeshwari', '/mandals/tambdi-jogeshwari/3.jpg', 'Tambdi Jogeshwari Ganpati, Pune', 'DesiBoy101 / CC BY 4.0 via Wikimedia Commons', 1200, 900, 2, false),
  ('tulshibaug-ganpati', '/mandals/tulshibaug-ganpati/1.jpg', 'Tulshibaug Ganpati, Pune', 'ANI(GM) / CC BY-SA 3.0 via Wikimedia Commons', 1200, 1600, 0, true),
  ('tulshibaug-ganpati', '/mandals/tulshibaug-ganpati/2.jpg', 'Tulshibaug Ganpati, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 1600, 1, false),
  ('tulshibaug-ganpati', '/mandals/tulshibaug-ganpati/3.jpg', 'Tulshibaug Ganpati, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 1600, 2, false),
  ('guruji-talim', '/mandals/guruji-talim/1.jpg', 'Guruji Talim Ganpati, Pune', 'ANI(GM) / CC BY-SA 3.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('guruji-talim', '/mandals/guruji-talim/2.jpg', 'Guruji Talim Ganpati, Pune', 'Suraj.patekar / CC BY-SA 3.0 via Wikimedia Commons', 1200, 800, 1, false),
  ('guruji-talim', '/mandals/guruji-talim/3.jpg', 'Guruji Talim Ganpati, Pune', 'Suraj.patekar / CC BY-SA 3.0 via Wikimedia Commons', 1200, 800, 2, false),
  ('hutatma-babu-genu-mandal', '/mandals/hutatma-babu-genu-mandal/1.jpg', 'Hutatma Babu Genu Mandal, Pune', 'Pooja Jadhav / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('hutatma-babu-genu-mandal', '/mandals/hutatma-babu-genu-mandal/2.jpg', 'Hutatma Babu Genu Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 1, false),
  ('hutatma-babu-genu-mandal', '/mandals/hutatma-babu-genu-mandal/3.jpg', 'Hutatma Babu Genu Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 2, false),
  ('shanipar-mandal', '/mandals/shanipar-mandal/1.jpg', 'Shanipar Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('shanipar-mandal', '/mandals/shanipar-mandal/2.jpg', 'Shanipar Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 1, false),
  ('shanipar-mandal', '/mandals/shanipar-mandal/3.jpg', 'Shanipar Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 2, false),
  ('nimbalkar-talim-mandal', '/mandals/nimbalkar-talim-mandal/1.jpg', 'Nimbalkar Talim Mandal, Pune', 'DesiBoy101 / CC BY-SA 4.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('jilbya-maruti-mandal', '/mandals/jilbya-maruti-mandal/1.jpg', 'Jilbya Maruti Mandal, Pune', 'ANI(GM) / CC BY-SA 3.0 via Wikimedia Commons', 1200, 900, 0, true),
  ('jilbya-maruti-mandal', '/mandals/jilbya-maruti-mandal/2.jpg', 'Jilbya Maruti Mandal, Pune', 'Suyashjust4u / CC BY 3.0 via Wikimedia Commons', 1200, 900, 1, false),
  ('jilbya-maruti-mandal', '/mandals/jilbya-maruti-mandal/3.jpg', 'Jilbya Maruti Mandal, Pune', 'Suyashjust4u / CC BY 3.0 via Wikimedia Commons', 1200, 1695, 2, false)
) as v(slug, url, alt, credit, width, height, sort_order, is_primary)
join ganpatis g on g.slug = v.slug;
