// GENERATED by scripts/emit-extra-roads.mjs — do not hand-edit.
//
// Road geometry from OpenStreetMap, © OpenStreetMap contributors, ODbL.
//
// Closures the police tracker publishes no line for. Each is emitted
// only when the OSM road reaches the junction the notice names, so the
// extent drawn is the extent ordered rather than whatever shares a name.

export interface ExtraRoad {
  /** The notice's spelling, so it matches VISARJAN_CLOSURES. */
  road: string;
  /** What OSM calls it, kept so a wrong match can be spotted. */
  osmName: string;
  /** The junction from the notice this was checked against. */
  anchor: string;
  /** How close the road gets to that junction, in metres. */
  reachM: number;
  /** Where the drawn line starts, when it is shorter than the notice's. */
  trimmedAt: string | null;
  segments: [number, number][][];
}

export const EXTRA_ROADS: ExtraRoad[] = [{"road":"Jangli Maharaj Road","osmName":"Jangli Maharaj Path","anchor":"Khandojibaba Chowk","reachM":7,"trimmedAt":"the Ghole Road junction","segments":[[[73.842195,18.515492],[73.842198,18.51545],[73.8422,18.515427],[73.842331,18.514941],[73.842388,18.51473],[73.842395,18.514703]],[[73.84776,18.522334],[73.847713,18.522284],[73.847287,18.521802],[73.846778,18.521191],[73.846227,18.520512],[73.846198,18.520475],[73.845968,18.520181],[73.845931,18.520134],[73.845741,18.519907],[73.845586,18.519723],[73.84554,18.519667],[73.84551,18.51963],[73.84523,18.519288],[73.845217,18.519272],[73.845074,18.519098],[73.845058,18.519078],[73.844945,18.518943],[73.844875,18.51886],[73.844514,18.518433],[73.844453,18.518361],[73.844333,18.518227],[73.844168,18.51804],[73.844058,18.517917],[73.843936,18.51778],[73.843868,18.517704],[73.843389,18.517174],[73.84332,18.517098],[73.843278,18.517044],[73.843197,18.516942],[73.843132,18.51686],[73.842983,18.516668],[73.842846,18.516496],[73.842667,18.516271],[73.842628,18.516217],[73.842566,18.516141],[73.84246,18.516004],[73.842409,18.515934]],[[73.842409,18.515934],[73.842308,18.515778],[73.842285,18.515744]],[[73.842395,18.514703],[73.842411,18.514619],[73.842416,18.514594]],[[73.848184,18.522778],[73.848085,18.522675],[73.84776,18.522334]],[[73.842416,18.514594],[73.842441,18.514516]]]}];
