// GENERATED by scripts/emit-checkpoint-geometry.mjs — do not hand-edit.
//
// Positions from OpenStreetMap, © OpenStreetMap contributors, ODbL.
//
// Only the chowks that sit ON the drawn procession corridor are here.
// A name match alone is not evidence — searching these names once put
// "Tilak Chowk" in Nigdi — so each was checked against Laxmi Road itself
// and anything further than 350 m from it was rejected. The
// times come from the mandal's schedule in ./visarjan.ts and are not
// repeated here, so the two cannot drift apart.

export interface CheckpointPoint {
  /** Matches a checkpoint time in MANDAL_ROUTE_SCHEDULES. */
  time: string;
  place: string;
  placeMr: string;
  /** What OSM calls it, kept so a wrong match can be spotted. */
  osmName: string;
  /** Distance from the drawn corridor, in metres. */
  offCorridorM: number;
  lat: number;
  lng: number;
}

export const CHECKPOINT_POINTS: CheckpointPoint[] = [
  {
    "time": "09:30",
    "place": "Lokmanya Tilak Putala (Mandai)",
    "placeMr": "लोकमान्य टिळक पुतळा (मंडई)",
    "osmName": "Mandai Chowk (Pune City Traffic Police closure map)",
    "offCorridorM": 194,
    "lng": 73.855866,
    "lat": 18.513445
  },
  {
    "time": "10:15",
    "place": "Belbaug Chowk",
    "placeMr": "बेलबाग चौक",
    "osmName": "Belbag Chowk",
    "offCorridorM": 0,
    "lng": 73.856287,
    "lat": 18.515669
  },
  {
    "time": "10:40",
    "place": "Ganpati Chowk",
    "placeMr": "गणपती चौक",
    "osmName": "Ganpati Chowk",
    "offCorridorM": 0,
    "lng": 73.85498,
    "lat": 18.515008
  },
  {
    "time": "11:15",
    "place": "Shri Limbraj Maharaj Chowk (Vaibhav Chowk)",
    "placeMr": "श्री लिंबराज महाराज चौक (वैभव चौक)",
    "osmName": "read off Google Maps",
    "offCorridorM": 6,
    "lng": 73.853787,
    "lat": 18.514498
  },
  {
    "time": "11:45",
    "place": "Kunte Chowk",
    "placeMr": "कुंटे चौक",
    "osmName": "Kunte Chowk",
    "offCorridorM": 0,
    "lng": 73.852318,
    "lat": 18.514475
  },
  {
    "time": "12:35",
    "place": "Umbrya Ganpati Chowk",
    "placeMr": "उंबऱ्या गणपती चौक",
    "osmName": "read off Google Maps",
    "offCorridorM": 0,
    "lng": 73.850118,
    "lat": 18.514183
  },
  {
    "time": "13:00",
    "place": "Bhanuvilas Chowk",
    "placeMr": "भानुविलास चौक",
    "osmName": "read off Google Maps",
    "offCorridorM": 2,
    "lng": 73.848466,
    "lat": 18.514001
  },
  {
    "time": "13:45",
    "place": "Vijay Talkies Chowk",
    "placeMr": "विजय टॉकीज चौक",
    "osmName": "Vijay Talkies",
    "offCorridorM": 0,
    "lng": 73.846161,
    "lat": 18.513728
  },
  {
    "time": "14:30",
    "place": "Garud Ganpati Chowk",
    "placeMr": "गरूड गणपती चौक",
    "osmName": "Garud Ganapati Mandir",
    "offCorridorM": 40,
    "lng": 73.845628,
    "lat": 18.513661
  },
  {
    "time": "14:45",
    "place": "Tilak Chowk",
    "placeMr": "टिळक चौक",
    "osmName": "read off Google Maps",
    "offCorridorM": 7,
    "lng": 73.843883,
    "lat": 18.512862
  }
];

/** How many the schedule lists, placed or not. */
export const TOTAL_CHECKPOINTS = 10;
